### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by 2240124355** [Artiprocher/sd-webui-fastblend#2]
GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v --filter=blob:none -- https://github.com/Artiprocher/sd-webui-fastblend G:\sd-webui\novelai\tmp\sd-webui-fastblend stderr: 'Cloning into 'G:\sd-webui\novelai\tmp\sd-webui-fastblend'... fatal: unable to access 'https://github.com/Artiprocher/sd-webui-fastblend/': OpenSSL SSL_read: Connection was reset, errno 10054 '

**Comment by Artiprocher** [comment]
This error is caused by your network environment, not this extension. If you are in China or other area that cannot connect to GitHub easily, you need to use a proxy server and try again.

**Comment by 2240124355** [comment]
I'm sorry, I just found out I didn't install git.
